{
 "title": "Honeypot",
 "panels": [
  {
   "title": "Page Loads",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(loadID)\nFROM loads\nWHERE\n  $__unixEpochFilter(date)"
    }
   ]
  },
  {
   "title": "Page Loads",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  ipAddress as 'IP Address',\n  host as 'Web Host',\n  location as 'Location',\n  useragent as 'User Agent'\nFROM loads\nWHERE\n  $__unixEpochFilter(date)"
    }
   ]
  },
  {
   "title": "Loads by IP",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  ipAddress as 'IP Address',\n  COUNT(*) as Count\nFROM loads \nWHERE\n  $__unixEpochFilter(date)\nGROUP BY ipAddress \nORDER BY Count DESC;\n"
    }
   ]
  },
  {
   "title": "Login Attempts",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(attemptID)\nFROM login_attempts\nWHERE\n  $__unixEpochFilter(date)"
    }
   ]
  },
  {
   "title": "Login Attempts",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 6, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS 'time',\n  ipAddress as 'IP Address',\n  host as 'Web Host',\n  username as 'Username',\n  password as 'Password'\nFROM login_attempts\nWHERE\n  $__unixEpochFilter(date)"
    }
   ]
  },
  {
   "title": "Loads by IP",
   "type": "table",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  ipAddress as 'IP Address',\n  COUNT(*) as Count\nFROM login_attempts \nWHERE\n  $__unixEpochFilter(date)\nGROUP BY ipAddress \nORDER BY Count DESC;\n"
    }
   ]
  },
  {
   "title": "Username by Use",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 5, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT \n  username as 'Username',\n  COUNT(*) as Count\nFROM login_attempts \nWHERE\n  $__unixEpochFilter(date)\nGROUP BY username \nORDER BY Count DESC;\n"
    }
   ]
  },
  {
   "title": "Password by Use",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT \n  password as 'Password',\n  COUNT(*) as Count\nFROM login_attempts \nWHERE\n  $__unixEpochFilter(date)\nGROUP BY password \nORDER BY Count DESC;\n"
    }
   ]
  }
 ]
}